### ISSUE TITLE
Class 'Auth_OpenID_Server' not found

### ISSUE THREAD

**Issue by Spomky** [arnaud-lb/AlbOpenIDServerBundle#4]
I have the following error: 
  Class 'Auth_OpenID_Server' not found in /home/virtual/1/web/app/cache/dev/appDevDebugProjectContainer.php

Does anyone know how to resolv it?

I installed step by step the bundle, cleared the cache but I does not anderstand where is my error?

**Comment by mrandmrssmith** [comment]
The php-openid library uses the PEAR naming convention. To autoload these classes you need to register the 'Auth' prefix with the Symfony class loader:

# app/autoload.php

$loader->registerPrefixes(array(
    ...
    'Auth_'            => **DIR**.'/../vendor/openid/php-openid',
));
